//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NimbusServer.Api.SellsPay {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SellsResult", Namespace="http://paytrue.com/")]
    [System.SerializableAttribute()]
    public partial class SellsResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool HasErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NimbusServer.Api.SellsPay.MerchantSellsDTO[] MerchantSellsField;
        
        private System.DateTime DateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool HasError {
            get {
                return this.HasErrorField;
            }
            set {
                if ((this.HasErrorField.Equals(value) != true)) {
                    this.HasErrorField = value;
                    this.RaisePropertyChanged("HasError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public NimbusServer.Api.SellsPay.MerchantSellsDTO[] MerchantSells {
            get {
                return this.MerchantSellsField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantSellsField, value) != true)) {
                    this.MerchantSellsField = value;
                    this.RaisePropertyChanged("MerchantSells");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MerchantSellsDTO", Namespace="http://paytrue.com/")]
    [System.SerializableAttribute()]
    public partial class MerchantSellsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantNameField;
        
        private long ApprovedTrxsCountField;
        
        private long RejectedTrxsCountField;
        
        private double ApprovedTrxsAmountField;
        
        private double RejectedTrxsAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MerchantCode {
            get {
                return this.MerchantCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantCodeField, value) != true)) {
                    this.MerchantCodeField = value;
                    this.RaisePropertyChanged("MerchantCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MerchantName {
            get {
                return this.MerchantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantNameField, value) != true)) {
                    this.MerchantNameField = value;
                    this.RaisePropertyChanged("MerchantName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long ApprovedTrxsCount {
            get {
                return this.ApprovedTrxsCountField;
            }
            set {
                if ((this.ApprovedTrxsCountField.Equals(value) != true)) {
                    this.ApprovedTrxsCountField = value;
                    this.RaisePropertyChanged("ApprovedTrxsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long RejectedTrxsCount {
            get {
                return this.RejectedTrxsCountField;
            }
            set {
                if ((this.RejectedTrxsCountField.Equals(value) != true)) {
                    this.RejectedTrxsCountField = value;
                    this.RaisePropertyChanged("RejectedTrxsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double ApprovedTrxsAmount {
            get {
                return this.ApprovedTrxsAmountField;
            }
            set {
                if ((this.ApprovedTrxsAmountField.Equals(value) != true)) {
                    this.ApprovedTrxsAmountField = value;
                    this.RaisePropertyChanged("ApprovedTrxsAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double RejectedTrxsAmount {
            get {
                return this.RejectedTrxsAmountField;
            }
            set {
                if ((this.RejectedTrxsAmountField.Equals(value) != true)) {
                    this.RejectedTrxsAmountField = value;
                    this.RaisePropertyChanged("RejectedTrxsAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://paytrue.com/", ConfigurationName="SellsPay.SellsSoap")]
    public interface SellsSoap {
        
        // CODEGEN: Generating message contract since element name GetCurrentSellsResult from namespace http://paytrue.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://paytrue.com/GetCurrentSells", ReplyAction="*")]
        NimbusServer.Api.SellsPay.GetCurrentSellsResponse GetCurrentSells(NimbusServer.Api.SellsPay.GetCurrentSellsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://paytrue.com/GetCurrentSells", ReplyAction="*")]
        System.Threading.Tasks.Task<NimbusServer.Api.SellsPay.GetCurrentSellsResponse> GetCurrentSellsAsync(NimbusServer.Api.SellsPay.GetCurrentSellsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentSellsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentSells", Namespace="http://paytrue.com/", Order=0)]
        public NimbusServer.Api.SellsPay.GetCurrentSellsRequestBody Body;
        
        public GetCurrentSellsRequest() {
        }
        
        public GetCurrentSellsRequest(NimbusServer.Api.SellsPay.GetCurrentSellsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCurrentSellsRequestBody {
        
        public GetCurrentSellsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentSellsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentSellsResponse", Namespace="http://paytrue.com/", Order=0)]
        public NimbusServer.Api.SellsPay.GetCurrentSellsResponseBody Body;
        
        public GetCurrentSellsResponse() {
        }
        
        public GetCurrentSellsResponse(NimbusServer.Api.SellsPay.GetCurrentSellsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paytrue.com/")]
    public partial class GetCurrentSellsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NimbusServer.Api.SellsPay.SellsResult GetCurrentSellsResult;
        
        public GetCurrentSellsResponseBody() {
        }
        
        public GetCurrentSellsResponseBody(NimbusServer.Api.SellsPay.SellsResult GetCurrentSellsResult) {
            this.GetCurrentSellsResult = GetCurrentSellsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SellsSoapChannel : NimbusServer.Api.SellsPay.SellsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SellsSoapClient : System.ServiceModel.ClientBase<NimbusServer.Api.SellsPay.SellsSoap>, NimbusServer.Api.SellsPay.SellsSoap {
        
        public SellsSoapClient() {
        }
        
        public SellsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SellsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SellsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SellsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NimbusServer.Api.SellsPay.GetCurrentSellsResponse NimbusServer.Api.SellsPay.SellsSoap.GetCurrentSells(NimbusServer.Api.SellsPay.GetCurrentSellsRequest request) {
            return base.Channel.GetCurrentSells(request);
        }
        
        public NimbusServer.Api.SellsPay.SellsResult GetCurrentSells() {
            NimbusServer.Api.SellsPay.GetCurrentSellsRequest inValue = new NimbusServer.Api.SellsPay.GetCurrentSellsRequest();
            inValue.Body = new NimbusServer.Api.SellsPay.GetCurrentSellsRequestBody();
            NimbusServer.Api.SellsPay.GetCurrentSellsResponse retVal = ((NimbusServer.Api.SellsPay.SellsSoap)(this)).GetCurrentSells(inValue);
            return retVal.Body.GetCurrentSellsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NimbusServer.Api.SellsPay.GetCurrentSellsResponse> NimbusServer.Api.SellsPay.SellsSoap.GetCurrentSellsAsync(NimbusServer.Api.SellsPay.GetCurrentSellsRequest request) {
            return base.Channel.GetCurrentSellsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NimbusServer.Api.SellsPay.GetCurrentSellsResponse> GetCurrentSellsAsync() {
            NimbusServer.Api.SellsPay.GetCurrentSellsRequest inValue = new NimbusServer.Api.SellsPay.GetCurrentSellsRequest();
            inValue.Body = new NimbusServer.Api.SellsPay.GetCurrentSellsRequestBody();
            return ((NimbusServer.Api.SellsPay.SellsSoap)(this)).GetCurrentSellsAsync(inValue);
        }
    }
}
